name: safe_ways
description: SafeWays is an application that finds the safest path for pedestrians, bicyclists, and drivers who mainly reside in the City of Los Angeles

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  cloud_firestore: any
  firebase_auth: ^0.18.1+2
  google_maps_flutter: ^1.0.6
  flutter_map: ^0.10.1+1
  google_maps_webservice: ^0.0.18
  http: ^0.12.2
  intl: ^0.16.1
  uuid: ^2.2.2
  geolocator: ^6.1.7
  provider: ^4.3.2+2
  flutter_google_places: ^0.2.6
  geoflutterfire: any
  get_it: ^5.0.1
  shared_preferences: ^0.5.12+2
  flutter_spinkit: ^4.1.2+1
  avatar_glow: ^1.2.0
  geocoder: ^0.2.1
  location: ^3.2.4
  weather: ^1.2.4
  google_fonts: ^1.1.1
  curved_navigation_bar: ^0.3.7
  flutter_html: ^1.2.0
  flutter_typeahead: ^2.0.0
  tuple: ^1.0.3
  bubble_bottom_bar: ^1.2.0
  floating_action_bubble: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-ThinItalic.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Black.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
